name: 'LegacyCraftPlugin'
version: '${version}'
main: xyz.lncvrt.legacycraftplugins.onepointsixplugin.LegacyCraftPlugin
commands:
  spawn:
    usage: /spawn
  rules:
    usage: /rules
  discord:
    usage: /discord